"""add notification type

Revision ID: 1c3f77b90371
Revises: 9ae4d1a41c38
Create Date: 2026-04-20 21:11:36.006746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3f77b90371'
down_revision: Union[str, Sequence[str], None] = '9ae4d1a41c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_follow', 'follows', ['follower_id', 'following_id'])
    op.add_column('notifications', sa.Column('notification_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_column('notifications', 'notification_type')
    op.drop_constraint('unique_follow', 'follows', type_='unique')
    # ### end Alembic commands ###
