"""add sender_id

Revision ID: b5954196e8f6
Revises: 1c3f77b90371
Create Date: 2026-04-20 22:54:14.634735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5954196e8f6'
down_revision: Union[str, Sequence[str], None] = '1c3f77b90371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notifications', 'sender_id')
    # ### end Alembic commands ###
