"""add post, comment ids

Revision ID: ce424d9af0df
Revises: b5954196e8f6
Create Date: 2026-04-20 23:29:13.948307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce424d9af0df'
down_revision: Union[str, Sequence[str], None] = 'b5954196e8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_comment_id'), 'notifications', ['comment_id'], unique=False)
    op.create_index(op.f('ix_notifications_post_id'), 'notifications', ['post_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_post_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_comment_id'), table_name='notifications')
    op.drop_column('notifications', 'comment_id')
    op.drop_column('notifications', 'post_id')
    # ### end Alembic commands ###
