"""add avatar url

Revision ID: ead819581c2e
Revises: 9ecfc7bd2905
Create Date: 2026-04-22 11:26:40.194433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead819581c2e'
down_revision: Union[str, Sequence[str], None] = '9ecfc7bd2905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_avatar_url'), 'users', ['avatar_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_avatar_url'), table_name='users')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
